export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const GET_AUTH_USER = 'GET_AUTH_USER'
export const GET_AUTH_USER_FAILURE = 'GET_AUTH_USER_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOG_OUT = 'LOG_OUT'

export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const GET_PROFILES = 'GET_PROFILES'
export const GET_PROFILES_FAILURE = 'GET_PROFILES_FAILURE'

export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID'
export const GET_PROFILE_BY_ID_FAILURE = 'GET_PROFILE_BY_ID_FAILURE'